// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27Iu89JsNtFrllsP7DSOycLjNZ1KU7UQ',
    appId: '1:225886549644:web:1570422bdacedc50ff6da9',
    messagingSenderId: '225886549644',
    projectId: 'chat-bot-api-ffdeb',
    authDomain: 'chat-bot-api-ffdeb.firebaseapp.com',
    databaseURL: 'https://chat-bot-api-ffdeb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-bot-api-ffdeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZrJKDiTwInetcXcjviFJSFLLIlQZNfbU',
    appId: '1:225886549644:android:110182e2bbb847e3ff6da9',
    messagingSenderId: '225886549644',
    projectId: 'chat-bot-api-ffdeb',
    databaseURL: 'https://chat-bot-api-ffdeb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-bot-api-ffdeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyERknRsxytKqv9ZXCnHoo3pVTGi7WCX4',
    appId: '1:225886549644:ios:4d496037a9166bb3ff6da9',
    messagingSenderId: '225886549644',
    projectId: 'chat-bot-api-ffdeb',
    databaseURL: 'https://chat-bot-api-ffdeb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-bot-api-ffdeb.appspot.com',
    iosClientId: '225886549644-iq3m0mb7covmasern5lau4v4adbj8em2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyERknRsxytKqv9ZXCnHoo3pVTGi7WCX4',
    appId: '1:225886549644:ios:5f9af2535690727dff6da9',
    messagingSenderId: '225886549644',
    projectId: 'chat-bot-api-ffdeb',
    databaseURL: 'https://chat-bot-api-ffdeb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-bot-api-ffdeb.appspot.com',
    iosClientId: '225886549644-btg0nsggl8b1etk48r2fc3ffveij47p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBot.RunnerTests',
  );
}
